package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/zeroboat/vuln-checker/agent/internal/collector"
	"github.com/zeroboat/vuln-checker/agent/internal/metrics"
)

type Client struct {
	ServerURL string
	Token     string // 빈 문자열이면 enroll 전 상태
	HostID    int
	HTTP      *http.Client
}

func New(serverURL, token string, hostID int) *Client {
	return &Client{
		ServerURL: serverURL,
		Token:     token,
		HostID:    hostID,
		HTTP:      &http.Client{Timeout: 30 * time.Second},
	}
}

// Policy는 호스트 그룹별 점검·메트릭 주기 정책(Phase 6)이다. enroll과 heartbeat
// 응답 둘 다에 실려오므로, 에이전트는 재등록 없이 하트비트 시점마다 정책 변경을
// 반영할 수 있다.
type Policy struct {
	CheckIntervalSeconds   int `json:"check_interval_seconds"`
	MetricsIntervalSeconds int `json:"metrics_interval_seconds"`
}

type EnrollResponse struct {
	HostID int    `json:"host_id"`
	Token  string `json:"token"`
	Policy
}

type HeartbeatResponse struct {
	Status string `json:"status"`
	Policy
}

// Enroll exchanges the one-time code for a host-bound long-lived token.
// 코드는 서버에서 즉시 소진되므로 이 호출은 딱 한 번만 성공한다.
func (c *Client) Enroll(code, hostname, os_, distro string) (*EnrollResponse, error) {
	body, _ := json.Marshal(map[string]string{
		"code":     code,
		"hostname": hostname,
		"os":       os_,
		"distro":   distro,
	})
	resp, err := c.HTTP.Post(c.ServerURL+"/api/agents/enroll", "application/json", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("enroll request: %w", err)
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusCreated {
		return nil, fmt.Errorf("enroll failed (%d): %s", resp.StatusCode, string(respBody))
	}

	var out EnrollResponse
	if err := json.Unmarshal(respBody, &out); err != nil {
		return nil, fmt.Errorf("parse enroll response: %w", err)
	}
	return &out, nil
}

func (c *Client) authedPost(path string, payload any) (*http.Response, error) {
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("marshal payload: %w", err)
	}
	req, err := http.NewRequest(http.MethodPost, fmt.Sprintf("%s%s", c.ServerURL, path), bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Token "+c.Token)
	return c.HTTP.Do(req)
}

// PostResults pushes one CheckRun's worth of results. run.RunID must be
// generated by the caller BEFORE main.sh executes and persisted to disk,
// so a retry after a crash reuses the same run_id instead of minting a new
// one from the result file (Codex 교차검증: idempotency는 실행 시작 시점의
// run ID 영속화가 핵심 — 결과 파일을 다시 읽어 새 키를 만들면 중복 방지가 깨짐).
func (c *Client) PostResults(run *collector.CheckRunPayload) error {
	path := fmt.Sprintf("/api/agents/%d/results", c.HostID)
	resp, err := c.authedPost(path, run)
	if err != nil {
		return fmt.Errorf("post results: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated && resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("post results failed (%d): %s", resp.StatusCode, string(body))
	}
	return nil
}

func (c *Client) PostHeartbeat() (*HeartbeatResponse, error) {
	path := fmt.Sprintf("/api/agents/%d/heartbeat", c.HostID)
	resp, err := c.authedPost(path, map[string]string{})
	if err != nil {
		return nil, fmt.Errorf("post heartbeat: %w", err)
	}
	defer resp.Body.Close()
	respBody, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("post heartbeat failed (%d): %s", resp.StatusCode, string(respBody))
	}
	var out HeartbeatResponse
	if err := json.Unmarshal(respBody, &out); err != nil {
		return nil, fmt.Errorf("parse heartbeat response: %w", err)
	}
	return &out, nil
}

func (c *Client) PostMetrics(samples []metrics.Sample) error {
	if len(samples) == 0 {
		return nil
	}
	path := fmt.Sprintf("/api/agents/%d/metrics", c.HostID)
	resp, err := c.authedPost(path, map[string]any{"samples": samples})
	if err != nil {
		return fmt.Errorf("post metrics: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("post metrics failed (%d): %s", resp.StatusCode, string(body))
	}
	return nil
}
