"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 로컬 dev(manage.py runserver)에서는 기본값을 쓰고, 컨테이너에서는 .env로 반드시 덮어쓴다.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure--nfrf^+z3+ixe+8ad127hi8gfq1k56at5ucq0j@qz^jjzlu6qj',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'monitor',
]

REST_FRAMEWORK = {
    # enroll/results/heartbeat/metrics는 자체 토큰 인증(auth.authenticate_host)을 직접
    # 처리하므로 여기 안 걸림. list_hosts/host_history 같은 사람용 읽기 API만
    # SessionAuthentication으로 로그인 여부를 본다(Phase 6 RBAC).
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# POSTGRES_HOST가 설정되면(docker-compose 환경) Postgres를 쓰고, 없으면(로컬 dev) sqlite로
# 그대로 동작한다 — plan.md 결정(서버: PostgreSQL)을 컨테이너 배포에서만 강제한다.

if os.environ.get('POSTGRES_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'vulnchecker'),
            'USER': os.environ.get('POSTGRES_USER', 'vulnchecker'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ['POSTGRES_HOST'],
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# CheckResult.detail 암호화(at-rest) — SNMP community string, 파일 권한 등 실제 설정값이
# 그대로 남을 수 있어 plan.md 보안 고려사항에 따라 암호화한다(Phase 6).
# 로컬 dev 기본값은 고정 키(재현 가능하려고) — 운영에서는 반드시 .env로 덮어쓸 것.
FIELD_ENCRYPTION_KEY = os.environ.get(
    'FIELD_ENCRYPTION_KEY',
    'zP5LNlMHdJiPOcYK_VPEodD57MlJUOOnuqNZJuwl5c8=',
)

# RBAC — 대시보드는 로그인이 필요하고, admin의 로그인 화면을 그대로 재사용한다
# (별도 로그인 페이지를 새로 만들 필요 없음).
LOGIN_URL = '/admin/login/'


# Celery — 알림 발송을 요청-응답 밖에서 처리(Slack이 느리거나 죽어도 에이전트의
# results 제출이 안 막히도록). REDIS_URL이 없는 로컬 dev(manage.py runserver)에서는
# eager 모드(즉시 동기 실행)로 자동 전환 — Postgres/sqlite 자동 전환과 같은 패턴.
REDIS_URL = os.environ.get('REDIS_URL')
CELERY_BROKER_URL = REDIS_URL or 'memory://'
CELERY_RESULT_BACKEND = REDIS_URL or 'cache+memory://'
CELERY_TASK_ALWAYS_EAGER = not bool(REDIS_URL)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
