# Generated by Django 6.0.7 on 2026-07-24 01:31

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
                ('executed_at', models.DateTimeField()),
                ('pass_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=100)),
                ('expected_count', models.IntegerField(default=0)),
                ('actual_count', models.IntegerField(default=0)),
                ('run_id', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('distro', models.CharField(blank=True, max_length=100)),
                ('agent_token', models.CharField(default=monitor.models.generate_token, max_length=64, unique=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('standard', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL'), ('REVIEW', 'REVIEW')], max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('reference', models.JSONField(blank=True, default=dict)),
                ('derived_from_codes', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitor.checkrun')),
            ],
        ),
        migrations.CreateModel(
            name='DriftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('config_diff', models.TextField(blank=True)),
                ('content_version_changed', models.BooleanField(default=False)),
                ('check_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_events', to='monitor.checkresult')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=monitor.models.generate_enrollment_code, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_codes', to='monitor.host')),
            ],
        ),
        migrations.AddField(
            model_name='checkrun',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='monitor.host'),
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='monitor.hostgroup'),
        ),
        migrations.CreateModel(
            name='RemediationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remediation_text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved')], default='open', max_length=20)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('post_check_status', models.CharField(blank=True, max_length=10)),
                ('check_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_proposals', to='monitor.checkresult')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=20)),
                ('sub_dimension', models.CharField(blank=True, max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('kind', models.CharField(choices=[('gauge', 'gauge'), ('counter', 'counter')], default='gauge', max_length=10)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='monitor.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'metric_type', 'collected_at'], name='monitor_met_host_id_c0573f_idx')],
            },
        ),
    ]
