# Generated by Django 6.0.7 on 2026-07-24 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_pattern', models.CharField(blank=True, help_text="비워두면 전체 코드. 'U-'처럼 접두사로 쓰면 해당 표준 전체에 매치", max_length=50)),
                ('severity', models.CharField(choices=[('fail_only', 'FAIL만'), ('fail_review', 'FAIL + REVIEW')], default='fail_only', max_length=20)),
                ('channel', models.CharField(choices=[('slack', 'Slack')], default='slack', max_length=20)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_group', models.ForeignKey(blank=True, help_text='비워두면 전체 호스트에 적용', null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.hostgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('drift_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.driftevent')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.alertrule')),
            ],
        ),
    ]
