# Generated by Django 6.0.7 on 2026-07-27 01:46
# 손으로 재정렬: CreateModel(AgentToken) -> 데이터 이관 -> RemoveField(Host.agent_token)
# 순서로 바꿔서, 기존에 발급된 토큰(이미 등록된 에이전트들이 쓰고 있는 값)이
# 유실되지 않고 AgentToken 테이블로 그대로 옮겨가게 한다.

import django.db.models.deletion
import monitor.fields
import monitor.models
from django.db import migrations, models


def copy_agent_tokens_forward(apps, schema_editor):
    Host = apps.get_model('monitor', 'Host')
    AgentToken = apps.get_model('monitor', 'AgentToken')
    for host in Host.objects.all():
        AgentToken.objects.create(host=host, token=host.agent_token)


def copy_agent_tokens_backward(apps, schema_editor):
    Host = apps.get_model('monitor', 'Host')
    AgentToken = apps.get_model('monitor', 'AgentToken')
    for token in AgentToken.objects.filter(revoked_at__isnull=True).order_by('created_at'):
        Host.objects.filter(pk=token.host_id).update(agent_token=token.token)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('monitor', '0002_alertrule_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=monitor.models.generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='monitor.host')),
            ],
        ),
        migrations.RunPython(copy_agent_tokens_forward, copy_agent_tokens_backward),
        migrations.RemoveField(
            model_name='host',
            name='agent_token',
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='check_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='metrics_interval_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='viewer_group',
            field=models.ForeignKey(blank=True, help_text='이 그룹에 속한 사용자만 이 HostGroup의 호스트를 볼 수 있음(비워두면 전체 로그인 사용자에게 공개)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='detail',
            field=monitor.fields.EncryptedTextField(blank=True),
        ),
    ]
