# Generated by Django 6.0.7 on 2026-07-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_host_agent_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remediationproposal',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('acknowledged', 'acknowledged'), ('resolved', 'resolved')], db_index=True, default='open', max_length=20),
        ),
    ]
